
export function setLogContainer() {}
export function resetLogContainer() {}
export function narrateAttack() {}
export function narrateArmorPiercing() {}
export function narrateDamageSummary() {}
export function narrateUltimateActivation() {}
export function narrateFervorMax() {}
export function narratePoisonDamage() {}
export function narrateDeath() {}
export function narrateDraw() {}
export function narrateVictory() {}
export function narrateUltimateMultiplier() {}
export function narrateUltimateHeal() {}
export function narrateUltimateSteal() {}
export function narrateUltimateShield() {}
export function narrateUltimatePoison() {}
export function narrateAntiArmor() {}
export function narrateDragonSlayer() {}
export function narrateLightningRod() {}
export function narrateRevive() {}
export function narrateBlockHeal() {}
export function narrateWarlordBlock() {}
export function narrateReflectFull() {}
export function narrateThornArmor() {}
export function narrateIronSkin() {}
export function narrateLeechAbsorb() {}
export function narrateSacredVeilReady() {}
export function narrateBrokenMirrorReady() {}
export function narrateSoulThief() {}
export function narrateXenophobia() {}
export function narrateDragonSlayerReady() {}
export function narrateLightningRodReady() {}
export function narrateGrowth() {}
export function narrateVenom() {}
export function narrateRust() {}
export function narrateDoubleStrike() {}
export function narrateLeechDrain() {}
export function narrateShieldRecharge() {}
export function narrateGracefulStrikeReady() {}
export function narrateBerserker() {}
export function narrateLastStand() {}
export function narrateWarlordRegen() {}
export function narrateBerserkerFury() {}
export function narrateAntimatterReady() {}
export function narrateAntimatterDetonation() {}
